components:
  schemas:
    AcceptParam:
      properties:
        CHL_ORDNO:
          description: Channel order no.
          type: string
        CONFIRM_DT:
          description: '- Datetime when the order was accepted

            - Formatted by "yyyyMMddhhmmss"'
          type: string
        DELIVERY_TIME:
          description: Estimated duration to be delivered in minutes
          type: integer
        MNG_ORDNO:
          description: Order no.
          type: string
        ORD_CHL:
          description: Order channel code
          type: string
        POS_ORDNO:
          description: POS order no.
          type: string
        SHOP_CD:
          description: Store code
          type: string
        STATUS:
          description: Order status
          items:
            enum:
            - order_accepted
            - order_rejected
          type: array
      required:
      - SHOP_CD
      - ORD_CHL
      - MNG_ORDNO
      - CHL_ORDNO
      - STATUS
      type: object
    ListParam:
      properties:
        SHOP_CD:
          description: Store code
          type: string
      required:
      - SHOP_CD
      type: object
    Order:
      properties:
        CHL_ORDNO:
          description: Channel order no.
          type: string
        CMP_CD:
          description: Company code and fixed to 'BKJH'
          type: string
        CONSULT_NM:
          description: ''
          type: string
        CUST_COORD_LATI:
          description: Customer's latitude coordinates
          type: string
        CUST_COORD_LATI_KATEC:
          description: Customer's latitude coordinates for KATEC
          type: string
        CUST_COORD_LONGI:
          description: Customer's longitude coordinates
          type: string
        CUST_COORD_LONGI_KATEC:
          description: Customer's longitude coordinates for KATEC
          type: string
        CUST_ID:
          description: Customer ID
          type: string
        CUST_NM:
          description: Customer name
          type: string
        CUST_SECTOR_CD:
          description: Customer's sector code
          type: string
        CUST_TELNO:
          description: Customer phone number
          type: string
        DC_AMT:
          description: The total amount of the discount
          type: integer
        DELAY_TIME:
          description: Delayed time
          type: string
        DLV_AMT:
          description: The total amount for delivery
          type: integer
        DLV_LOT_NUM_ADDR:
          description: Address to deliver
          type: string
        DLV_ROADNM_ADDR:
          description: Road name address to deliver
          type: string
        DLV_TIME:
          description: Delivery time
          type: string
        ITEM_CNT:
          description: The quantity of the menu
          type: integer
        MEMO:
          description: Memo
          type: string
        MNG_ORDNO:
          description: Order no.
          type: string
        NET_SALE_AMT:
          description: The total amount of the net sale
          type: integer
        OCB_DC_AMT:
          description: The total OCB amount of the discount
          type: integer
        ORD_CHL:
          description: Order channel code
          type: string
        ORD_DATE:
          description: '- Datetime when the order was created

            - Formatted by "yyyyMMddhhmmss"'
          type: string
        ORD_STATUS:
          description: Status of the order
          type: string
        ORD_TYPE:
          description: "Order type\n  - 01: In restaurant\n  - 02: To go\n  - 03:\
            \ Drive through\n  - 04: Delivery"
          type: string
        PAY_AMT:
          description: The paid total price
          type: integer
        PAY_CNT:
          description: The count of the payment
          type: integer
        PAY_STATUS:
          description: "The payment status\n  - 01: Pay later\n  - 02: Prepaid"
          type: string
        POST_NO:
          description: The post code
          type: string
        POS_ORDNO:
          description: POS order no.
          type: string
        PROMO_DC_AMT:
          description: The total amount of the promotion discount
          type: integer
        RESERV_ORD_DATE:
          description: Reservation datetime when the order should be delivered or
            picked up
          type: string
        SALES_ORG_CD:
          description: Sales org. code and fixed to '2100'
          type: string
        SHOP_CD:
          description: Store code
          type: string
      type: object
    ResultDTO:
      properties:
        resultCode:
          description: "Result code from ```[000, 500, ...]```.\n  - 000: Success\n\
            \  - 500: Failed for business logical or systemic errors\n  - Other codes:\
            \ Failed for other reasons"
          type: string
        resultList:
          description: Result data as List of 'Order'
          items:
            $ref: '#/components/schemas/Order'
          type: array
        resultMap:
          description: Result data as Map
          type: object
        resultMessage:
          description: Result message
          type: string
      type: object
externalDocs:
  description: https://www.burgerking.co.jp
  url: Find out more about this API
info:
  contact:
    email: apiteam@burgerking.co.jp
    name: API Integration Team
  description: Burger King Japan, the API Integration Document
  termsOfService: https://www.burgerking.co.jp
  title: '[FoodPanda] Burger King Japan, the API Integration Document'
  version: 1.0.0
openapi: 3.0.0
paths:
  /oms0001/accept.bkr:
    post:
      description: Accept the specified order
      operationId: acceptOrder
      parameters:
      - description: Unique key to identify client and BKJH provides it
        in: header
        name: Auth-Key
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/AcceptParam'
      responses:
        200:
          content:
            application/json;charset=utf-8: {}
          description: Success
        500:
          content:
            application/json;charset=utf-8: {}
          description: Internal Server Error
      summary: Accept the new order
      tags:
      - Order
  /oms0001/list.bkr:
    post:
      description: Get new order list
      operationId: getOrders
      parameters:
      - description: Unique key to identify client and BKJH provides it
        in: header
        name: Auth-Key
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/ListParam'
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/ResultDTO'
          description: Result of search new orders
        '500':
          content:
            application/json;charset=utf-8: {}
          description: Internal Server Error
      summary: Get new orders
      tags:
      - Order
servers:
- description: Production mode
  url: https://e-oms.burgerking.co.jp:9443
- description: Development mode
  url: https://dev-oms.burgerking.co.jp:9443
tags:
- description: Search and process the order data
  name: Order
- description: Search and process the store data
  name: Store
